; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:arduino_nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
upload_port = /dev/serial/by-id/usb-Arduino_NanoESP32_10B41DC5DA00-if01
monitor_port = /dev/serial/by-id/usb-Arduino_NanoESP32_10B41DC5DA00-if01
lib_deps = 
    me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    ArduinoJson
board_build.filesystem = littlefs
